

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringDemo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
